## Define the stages & order of execution

stages:
    - CLUSTER-SETUP
    - INFRA-SETUP
    - CLUSTER-CONNECT
    - CLUSTER-CLEANUP

## Setup kubernetes cluster using Rancher
cluster-create:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-SETUP
  script:
    - chmod 755 ./stages/cluster-setup/setup
    - ./stages/cluster-setup/setup

## Deploy Director On-Prem
director-deploy:
  image: harshshekhar15/gitlab-job:v2
  stage: INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/infra-setup/dop
    - ./stages/infra-setup/dop

pre-requisites:
  image: harshshekhar15/gitlab-job:v2
  stage: INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/infra-setup/pre-requisites
    - ./stages/infra-setup/pre-requisites

basic-sanity-checks:
  image: harshshekhar15/gitlab-job:v2
  stage: INFRA-SETUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/infra-setup/basic-sanity-checks
    - ./stages/infra-setup/basic-sanity-checks

create-api-key:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/create-apikey
    - ./stages/cluster-connect/create-apikey

cluster-connect:
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CONNECT
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-connect/cluster-connect
    - ./stages/cluster-connect/cluster-connect

e2e-metrics:
  when: always
  image: harshshekhar15/gitlab-job:v2
  stage: CLUSTER-CLEANUP
  dependencies:
    - cluster-create
  script:
    - chmod 755 ./stages/cluster-cleanup/e2e-metrics
    - ./stages/cluster-cleanup/e2e-metrics

## Revert the cluster to previous snapshot
cluster-cleanup:
  when: always
  image: harshshekhar15/gitlab-job:v2
  dependencies:
    - cluster-create
  stage: CLUSTER-CLEANUP
  script:
    - chmod 755 ./stages/cluster-cleanup/cleanup
    - ./stages/cluster-cleanup/cleanup